project_name: cf-alias
builds:
  - main: ./tools/goreleaser.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    hooks:
      post: ./tools/goreleaser-dist.sh {{ .Target }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - format_overrides:
    - goos: windows
      format: zip
    files:
      - completions/*
      - LICENSE
      - THIRDPARTY.md

signs:
  - artifacts: checksum
    args: ["-u", "6A34CFEE77FE8257C3BB92FE24C3FC5D6987904B", "--output", "${signature}", "--detach-sign", "${artifact}"]

brews:
  - tap:
      owner: dustinblackman
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/dustinblackman/cf-alias
    description: Create Cloudflare email alias' directly from your terminal or Alfred.
    test: |
      system "#{bin}/cf-alias --version"
    install: |
      # Install cf-alias
      bin.install "cf-alias"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "bash")
      (bash_completion/"cf-alias").write output

      output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "zsh")
      (zsh_completion/"_cf-alias").write output

      output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "fish")
      (fish_completion/"cf-alias.fish").write output

scoop:
  bucket:
    owner: dustinblackman
    name: scoop-bucket
  homepage: https://github.com/dustinblackman/cf-alias
  description: Create Cloudflare email alias' directly from your terminal or Alfred.
  license: MIT

nfpms:
  - homepage: https://github.com/dustinblackman/cf-alias
    description: Create Cloudflare email alias' directly from your terminal or Alfred.
    maintainer: Dustin Blackman
    vendor: Dustin Blackman
    formats:
      - deb
      - rpm
    contents:
      - src: ./completions/cf-alias.bash
        dst: /usr/share/bash-completion/completions/cf-alias
        file_info:
          mode: 0644
      - src: ./completions/cf-alias.fish
        dst: /usr/share/fish/completions/cf-alias.fish
        file_info:
          mode: 0644
      - src: ./completions/cf-alias.zsh
        dst:  /usr/share/zsh/vendor-completions/_cf-alias
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/languagetool-code-comments/copyright/LICENSE
        file_info:
          mode: 0644
      - src: ./THIRDPARTY.md
        dst: /usr/share/doc/languagetool-code-comments/copyright/THIRDPARTY.md
        file_info:
          mode: 0644

aurs:
  - name: cf-alias-bin
    homepage: https://github.com/dustinblackman/cf-alias
    description: Create Cloudflare email alias' directly from your terminal or Alfred.
    maintainers:
      - "Dustin Blackman"
    contributors:
      - "Dustin Blackman"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/cf-alias-bin.git"
    package: |-
        # bin
        install -Dm755 "./cf-alias" "${pkgdir}/usr/bin/cf-alias"

        # license
        install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/cf-alias/LICENSE"
        install -Dm644 "./THIRDPARTY.md" "${pkgdir}/usr/share/licenses/languagetool-code-comments/THIRDPARTY.md"

        # completions
        mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
        mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
        mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
        install -Dm644 "./completions/cf-alias.bash" "${pkgdir}/usr/share/bash-completion/completions/cf-alias"
        install -Dm644 "./completions/cf-alias.zsh" "${pkgdir}/usr/share/zsh/site-functions/_cf-alias"
        install -Dm644 "./completions/cf-alias.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/cf-alias.fish"

changelog:
  use: github-native
