[advisories]
git-fetch-with-cli = true

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
  "MIT",
  "Apache-2.0",
  "BSL-1.0",
  "BSD-3-Clause",
]
exceptions = [
  { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 },
]
